import { type, platform, arch, totalmem, freemem, cpus, uptime, homedir, tmpdir, hostname, release, version } from 'node:os' // Módulos nativos de Node.js (node:...)
console.log('Información del sistema operativo:')
console.log('-----------------------------------')

console.log(`Sistema operativo: ${type()}`)
console.log(`Plataforma: ${platform()}`)
console.log(`Arquitectura: ${arch()}`)
console.log(`Memoria total: ${totalmem()} bytes`)
console.log(`Memoria libre: ${freemem()} bytes`)
console.log(`Número de CPUs: ${cpus().length}`)
console.log(`Tiempo de actividad: ${uptime()} segundos`)
console.log(`Directorio de inicio: ${homedir()}`)
console.log(`Directorio temporal: ${tmpdir()}`)
// console.log(`Redes: ${JSON.stringify(os.networkInterfaces(), null, 2)}`)
console.log(`Hostname: ${hostname()}`)
console.log(`Release: ${release()}`)
console.log(`Version: ${version()}`)

console.log(`Tiempo del Ordenador Prendido: ${uptime() / 60 / 60}`)
