const os = require('node:os') // Módulos nativos de Node.js (node:...)
console.log('Información del sistema operativo:')
console.log('-----------------------------------')

console.log(`Sistema operativo: ${os.type()}`)
console.log(`Plataforma: ${os.platform()}`)
console.log(`Arquitectura: ${os.arch()}`)
console.log(`Memoria total: ${os.totalmem()} bytes`)
console.log(`Memoria libre: ${os.freemem()} bytes`)
console.log(`Número de CPUs: ${os.cpus().length}`)
console.log(`Tiempo de actividad: ${os.uptime()} segundos`)
console.log(`Directorio de inicio: ${os.homedir()}`)
console.log(`Directorio temporal: ${os.tmpdir()}`)
// console.log(`Redes: ${JSON.stringify(os.networkInterfaces(), null, 2)}`)
console.log(`Hostname: ${os.hostname()}`)
console.log(`Release: ${os.release()}`)
console.log(`Version: ${os.version()}`)

console.log(`Tiempo del Ordenador Prendido: ${os.uptime() / 60 / 60}`)
